plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "gemfiles/**/*"

Naming/FileName:
  Exclude:
    - "lib/paper_trail-human.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Lint/UnusedMethodArgument:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 35

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"

RSpec/VerifiedDoubleReference:
  Enabled: false
